# 1. Elegimos la imagen base. Usaremos la versión LTS de Node.js
FROM node:20-alpine

# 2. Creamos y establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# 3. Copiamos los archivos de dependencias para aprovechar el caché de Docker
COPY package*.json ./

# 4. Instalamos las dependencias
RUN npm install

# 5. Copiamos el resto del código de la aplicación
COPY . .

# 6. Exponemos el puerto que usa tu aplicación (asumimos el 3000 o 8080)
# Ajusta este número si tu Express corre en otro puerto
EXPOSE 3000

# 7. Comando para iniciar la aplicación cuando se ejecute el contenedor
CMD ["npm", "start"]